sudo: false
language: node_js

git:
    submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
  - git submodule update --init --recursive

node_js:
  - "10"

script:
  - npm run build;

deploy:
- provider: s3
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key: ${SECRET_ACCESS_KEY}
  bucket: staging.deepstream.io
  skip_cleanup: true
  acl: public_read
  local_dir: public
  upload-dir: ./
  on:
    branch: master
- provider: s3
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key: ${SECRET_ACCESS_KEY}
  bucket: releases.deepstream.io
  skip_cleanup: true
  acl: public_read
  local_dir: public
  upload-dir: ./
  on:
    tags: true

notifications:
  email: false